[tool.poetry]
name = "proyecto1"
version = "0.1.0"
description = "Mi primer proyecto de ciencia de datos"
authors = ["Jose"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
